= Qaclana

Qaclana is an experiment.

The goal is to build a Web Application Firewall, based in a different architecture to existing Web Application
Firewalls.

The main idea is to have the filter/proxy to be very slim: they open a web socket connection to the server and maintain
"some" state. When a request comes in, the meta data from the request is analyzed and a decision is made on whether
the request will be accepted or not.

In the background, the request data is sent to the server for further analysis. If the server decides that it doesn't
like whoever sent the request, the client's IP is added to a blacklist and this event is sent via web socket to all
proxy/filter instances. Further requests from this client will then be blocked.

ifdef::env-github[]
[link=https://jenkins.kroehling.de/job/qaclana/]
image:https://jenkins.kroehling.de/buildStatus/icon?job=qaclana["Build Status", link="https://jenkins.kroehling.de/job/qaclana/"]
endif::[]

== About Qaclana

The project is divided into several modules. More information about the individual modules can be found in the
respective module's README files.

* backend: it's the REST backend that is responsible for analysing request and response data. If a client is marked as
suspicious, a blacklist event is sent via Web Sockets to the registered instances.
* shared: code that is useful for more than one module.
* client: code that is intended to be shared between proxy and filter.
* filter: servlet filter that intercepts the requests and responses. Might block a request from coming in, or a response
from going out.
* proxy: similar in intention to the filter, but intended to be used by non-Java EE applications.

== Basic usage

At this point, there's no usage. In the future:

- the filter will be able to be embedded into Java EE applications. By just adding a dependency to the module and
"somehow" telling it where the server is should suffice.
- the proxy will be a standalone application (possibly based on Wildfly, Wildfly Swarm or Undertow).

== How to build Qaclana from source

The whole project can be built as a regular Gradle project:
[source,bash]
----
$ ./gradlew build
----

== Releasing

Coming soon.

== License

Qaclana is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----




