= Qaclana

Qaclana is an experiment.

The goal is to build a Web Application Firewall, based in a different architecture to existing Web Application
Firewalls.

The main idea is to have the filter/proxy to be very slim: they open a web socket connection to the server and maintain
"some" state. When a request comes in, the meta data from the request is analyzed and a decision is made on whether
the request will be accepted or not.

In the background, the request data is sent to the server for further analysis. If the server decides that it doesn't
like whoever sent the request, the client's IP is added to a blacklist and this event is sent via web socket to all
proxy/filter instances. Further requests from this client will then be blocked.

ifdef::env-github[]
[link=https://jenkins.kroehling.de/job/qaclana/]
image:https://jenkins.kroehling.de/buildStatus/icon?job=qaclana["Build Status", link="https://jenkins.kroehling.de/job/qaclana/"]
endif::[]

== About Qaclana

The project is divided into several modules. More information about the individual modules can be found in the
respective module's README files.

* link:add-ons[add-ons]: code that extends or improves the behavior of a basic service or processor, like batch jobs.
* link:api[api]: code that is useful for more than one module. Contains no big dependencies, but has Java EE as runtime target.
* link:backend[backend]: it's the REST backend that is responsible for analysing request and response data. If a client is marked as
suspicious, a blacklist event is sent via Web Sockets to the registered instances.
* link:example-filter[example-filter]: very simple JAX-RS application that incorporates the filter
* link:filter[filter]: servlet filter that intercepts the requests and responses. Might block a request from coming in, or a response
from going out.
* link:processors[processors]: request and response analyzers, responsible for the firewall outcome.
* link:services[services]: implementations of services defined on the API.
* link:proxy[proxy]: coming soon. The idea is to incorporate the filter into a reverse-proxy, so that this can be used by non
Java EE applications as well.

== Basic usage

* Deploy the backend WAR file onto a Wildfly 10 instance
* Consume the filter on your own Java EE application, deployed on the same or remote Wildfly 10 instance

== Architecture

Both the backend and the filter are heavily dependent on Java EE. EJBs and CDI beans are the key backbones of the
architecture. This allows for a very decoupled architecture, both in providers and for consumers. The main contract
among the modules is defined on the API module, as this is pretty much the only module that other modules can depend on.
The filter and the backend are also "assembler" modules, providing some basic features and extending themselves by
incorporating other modules. Whenever possible, CDI events are fired and can be observed by other modules. Events which
are part of the API are defined on the API module. Request and response processors should each reside on its own module,
and register themselves with the Processor registry via CDI as well.

As it currently is, the backend is a single point of failure. While it can be scaled by adding more backend instances
and put behind a load balancer, once a backend node goes down, all client Web Sockets are disconnected with it.

== How to build Qaclana from source

The whole project can be built as a regular Gradle project:
[source,bash]
----
$ ./gradlew build
----

== Releasing

Qaclana implements the idea of Continuous Deployment and Continuous Delivery. Each commit, once accepted into the main
git repository, becomes a version that is deployed on a Maven repository.

== License

Qaclana is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2016 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----
